name: "Generate and publish"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Minecraft version from the version manifest"
        required: true

jobs:
  generate-and-publish:
    name: Generate and publish for Minecraft ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install findutils
        run: apt install findutils
      - name: Generate and publish mappings
        run: ./gradlew publish -PminecraftVersion="${{ github.event.inputs.version }}" --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Update Quilt Meta
        uses: quiltmc/update-quilt-meta@main
        with:
          b2-key-id: ${{ secrets.META_B2_KEY_ID }}
          b2-key: ${{ secrets.META_B2_KEY }}
          cf-key: ${{ secrets.META_CF_KEY }}
